DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS profiles CASCADE;



CREATE TABLE users (
  id BIGSERIAL PRIMARY KEY,
  email VARCHAR NOT NULL UNIQUE,
  password_digest VARCHAR NOT NULL
);
CREATE TABLE profiles (
	id BIGSERIAL PRIMARY KEY,
	user_id BIGSERIAL REFERENCES users(id),
	name VARCHAR NOT NULL,
	hiTemp FLOAT NOT NULL,
	loTemp FLOAT NOT NULL,
	precip FLOAT NOT NULL,
	maxWind FLOAT NOT NULL,
	humidity FLOAT NOT NULL,
	cloudCover FLOAT NOT NULL
);
